global using System;
global using System.IO;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Collections;
global using System.Data;
global using System.Text.RegularExpressions;
global using System.Xml;
global using System.Xml.Serialization;
global using WpfApp_XML.Models;
global using WpfApp_XML.Services;
global using Excel = Microsoft.Office.Interop.Excel;
global using Word = Microsoft.Office.Interop.Word;
global using System.Diagnostics;
global using System.Reflection.Metadata;
global using OfficeOpenXml;